Data:
  data_root: 
  base_data_root: 
  train_list: ./lists/pascal/voc_sbd_merge_noduplicate.txt
  val_list: ./lists/pascal/val.txt
  classes: 2


Train:
  # Aug
  train_h: 473
  train_w: 473
  val_size: 473
  scale_min: 0.9  # minimum random scale
  scale_max: 1.1 # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  ignore_label: 255
  padding_label: 255
  # Dataset & Mode
  split: 0
  shot: 5
  data_set: 'pascal'
  use_split_coco: False # True means FWB setting
  # Optimizer
  batch_size: 4 # batch size for training (bs8 for 1GPU)
  base_lr: 0.0001 
  pre_weight: ./initmodel/PSPNet/pascal/split0/vgg/best.pth
  epochs: 200
  start_epoch: 0 
  stop_interval: 80 # stop when the best result is not updated for "stop_interval" epochs
  index_split: 0  # index for determining the params group with 10x learning rate
  power: 0.9 # 0 means no decay
  momentum: 0.9
  weight_decay: 0.01
  warmup: False
  # Viz & Save & Resume
  print_freq: 10
  save_freq: 10
  resume: 
  # Validate
  evaluate: True
  SubEpoch_val: True # val at the half epoch
  fix_random_seed_val: True
  batch_size_val: 1
  resized_val: True 
  ori_resize: True  # use original label for evaluation
  # Else
  workers: 8
  fix_bn: True
  manual_seed: 321
  seed_deterministic: False

Method:
  layers: 50
  vgg: True 
  aux_weight1: 1.0
  aux_weight2: 1.0 
  low_fea: 'layer2'  # low_fea for computing the Gram matrix
  kshot_trans_dim: 2 # K-shot dimensionality reduction
  merge: 'final'     # fusion scheme for GFSS ('base' Eq(S1) | 'final' Eq(18) )
  merge_tau: 0.9     # fusion threshold tau

Test_Finetune:
  weight: # Path to the test model
  ann_type: 'mask' # mask/bbox
